services:
  db-postgres:
    image: postgres:15-alpine
    container_name: arsal-postgres
    environment:
      POSTGRES_DB: chamadoaberto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: satell1tE
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - arsal-network
    # 🍏 Garante que o Docker sabe quando o banco está realmente pronto para receber dados
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chamadoaberto"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-chamados:
    build: .
    container_name: arsal-api
    ports:
      - "8081:8081"
    # 🛑 O segredo está aqui: A API agora ESPERA o banco passar no teste de saúde!
    depends_on:
      db-postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/chamadoaberto
    networks:
      - arsal-network

volumes:
  postgres_data:

networks:
  arsal-network:
    driver: bridge