spring.application.name=chamados-api

spring.datasource.url=jdbc:postgresql://ep-tiny-sun-atqalea9.c-g.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner


spring.datasource.username=neondb_owner


spring.datasource.driver-class-name=org.postgresql.Driver