spring.application.name=chamados-api


spring.datasource.url=jdbc:postgresql://ep-tiny-sun-atqalea9.c-g.us-east-1.aws.neon.tech/neondb?sslmode=require&options=endpoint%3Dep-tiny-sun-atqalea9


spring.datasource.username=neondb_owner


spring.datasource.password=npg_p6BOhY8EWIsG


spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=create


server.port=8081


spring.datasource.hikari.connection-timeout=30000
